services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inv_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "inv_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend

  api:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://inv_user:password123@db:5432/inventory_db
    networks:
      - backend

networks:
  backend:
    driver: bridge
